# Changes here will be overwritten by Copier
_commit: v0.3.0-beta
_src_path: https://github.com/VOLTTRON/copier-poetry-volttron-agent.git
author_email: mark.bonicillo@pnnl.gov
author_fullname: Mark Bonicillo
author_username: bonicim
copyright_date: '2022'
copyright_holder: Pacific Northwest National Lab
copyright_holder_email: volttron@pnnl.gov
copyright_license: Apache License 2.0
project_description: The Platform Driver agent is a special purpose agent a user can install on the platform to manage communication of the platform with devices. The Platform driver features a number of endpoints for collecting data and sending control signals using the message bus and automatically publishes data to the bus on a specified interval.
project_name: PlatformDriverAgent
python_agent_class_name: PlatformDriverAgent
python_package_command_line_name: platformdriveragent
python_package_distribution_name: volttron-platform-driver
python_package_import_name: platform_driver_agent
repository_name: platform-driver-agent
repository_namespace: VOLTTRON
repository_provider: github.com
use_precommit: true
